// <auto-generated />
using System;
using Encurtador_De_Links.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Encurtador_De_Links.Migrations;

[DbContext(typeof(LinkContext))]
partial class LinkContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.36")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("Encurtador_De_Links.Models.Link", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<DateTime>("DataHoraCriacao")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Encurtado")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<bool>("Inativo")
                    .HasColumnType("tinyint(1)");

                b.Property<string>("Original")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.HasKey("Id");

                b.ToTable("Links");
            });
#pragma warning restore 612, 618
    }
}
